version: 0.2
env:
  secrets-manager:
    SONAR_LOGIN: prod/x23340355/EcoGive:sonartoken
    SONAR_HOST_URL: prod/x23340355/EcoGive:HOST
    SONAR_ORGANIZATION: prod/x23340355/EcoGive:Organization
    SONAR_PROJECT_KEY: prod/x23340355/EcoGive:Project
    
phases:
  install:
    runtime-versions:
      python: 3.9
      java: corretto17  # Use Java 17 (Corretto)
    commands:
      - echo "Starting installation phase..."
      - pip install --upgrade pip
      - pip install -r requirements.txt
      #Install dependencies needed for running the static analysis
      - pip install pylint
      #Install for sonar-scanner
      - echo "Downloading SonarScanner..."
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      - unzip sonar-scanner-cli-5.0.1.3006-linux.zip
      - export PATH=$PATH:$(pwd)/sonar-scanner-5.0.1.3006-linux/bin
      - export JAVA_HOME=/usr/lib/jvm/java-17
      - export PATH=$JAVA_HOME/bin:$PATH
      
  pre_build:
    commands:
      - echo "Starting pre-build phase..."
      - python --version
      - echo "Running pylint on all python files of the project"
      - pylint $CODEBUILD_SRC_DIR/*.py
      - pylint $CODEBUILD_SRC_DIR/**/*.py
      - java -version  #Check if Java 17 is being used
      - which sonar-scanner  #Verify sonar-scanner installation
      - sonar-scanner -v  #Confirm sonar-scanner version
      
  build:
    commands:
      - echo "Starting build phase..."
      - python manage.py collectstatic --noinput
      - python manage.py migrate
      #for sonar analysis
      - echo "SONAR_PROJECT_KEY is: $SONAR_PROJECT_KEY"
      - echo "SONAR_ORGANIZATION is: $SONAR_ORGANIZATION"
      - echo "SONAR_HOST_URL is: $SONAR_HOST_URL"
      - echo "SONAR_TOKEN is: $SONAR_TOKEN"
      - java -version
      - echo "Running SonarCloud analysis..."
      - sonar-scanner -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.organization=$SONAR_ORGANIZATION -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN -X

  post_build:
    commands:
      - echo "Post-build phase completed."

artifacts:
  files:
    - '**/*'
