version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
      # Install dependencies needed for running the static analysis
      - pip install pylint
  pre_build:
    commands:
      - echo "Starting pre-build phase..."
      - python --version
      - echo "Running pylint on all python files of the project"
      - pylint $CODEBUILD_SRC_DIR/*.py
      - pylint $CODEBUILD_SRC_DIR/**/*.py
  build:
    commands:
      - echo "Starting build phase..."
      - python manage.py collectstatic --noinput
      - python manage.py migrate
  post_build:
    commands:
      - echo "Build complete."

artifacts:
  files:
    - '**/*'
