# Generated by Django 4.2.16 on 2024-11-20 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecogiveapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
