# Generated by Django 4.2.16 on 2024-11-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecogiveapp', '0002_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
